server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/survey?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: fusion!@34
  thymeleaf:
    check-template-location: false
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
        show_sql: true
        highlight_sql: true
        format_sql: true
        use_sql_comments: true

springdoc:
  packages-to-scan: com.toy.survey
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /api-info.html
    tags-sorter: alpha DESC
    operations-sorter: alpha

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace

jwt:
  expiration-time: 86400000
  secret: 5caf4c2febbf3b6f7e0b27138f403455f8a76e35f5524ac6d765a39682d23157
